-- Auto-generated by scenario_model.py. Loads model output into the schema.
-- Scenarios operate on the disclosed base; see methodology.md.

INSERT INTO dim_scenario (scenario_name, scenario_type, base_company_id, base_fiscal_year, conversion_multiple, sunset_window_months, description) VALUES
 ('A_1.25x', 'migration', 1, 2025, 1.25, 36, 'Subscription = 1.25x prior maintenance ARR'),
 ('B_1.50x', 'migration', 1, 2025, 1.5, 36, 'Subscription = 1.5x prior maintenance ARR'),
 ('C_2.00x', 'migration', 1, 2025, 2.0, 36, 'Subscription = 2.0x prior maintenance ARR');
